name: MS Teams Notification

on: 
  push:
  issue_comment:
  issues:
  milestone:
  registry_package:
  release:
  pull_request:
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Notify dedicated teams channel
        uses: aliencube/microsoft-teams-actions@v0.8.0
        with:
          webhook_uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
          summary: 'Message Summary'
          text: 'Message test'
          theme_color: 28a745
          sections: '[{ "activityTitle": "hello world" }]'
          actions: '[{ "@type": "OpenUri", "name": "lorem ipsum", "targets": [{ "os": "default", "uri": "https://localhost" }] }]'
